spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

logging:
  level:
    root: info
    io.github.balasis.taskmanager: INFO
    org.springframework.transaction.interceptor: WARN
    com.azure.identity: WARN
