# backend only — use alongside backend-db-compose + backend-blob-compose
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: taskmanager_backend
    env_file:
      - .env
    ports:
      - "8080:8080"
    restart: always
