FROM nginx:alpine

# Copy all frontend files into nginx html folder
COPY ./ usr/share/nginx/html

# Copy custom nginx config for dev (with proxy to backend)
COPY ./nginx.dev.conf /etc/nginx/conf.d/default.conf

EXPOSE 80