services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: taskmanager_mssql
    restart: always
    env_file:
      - .env
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "${DB_PASSWORD}"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql

volumes:
  mssql-data: