services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: taskmanager_mssql
    restart: always
    env_file:
      - .env
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "${DB_PASSWORD}"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
# recreate db ->
# docker exec -it taskmanager_mssql opt/mssql-tools18/bin/sqlcmd -S localhost -U SA -P '82468246aA!!!' -C -Q "CREATE DATABASE taskmanager_db;"
volumes:
  mssql-data: