spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev-h2}
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 550MB
  data:
    web:
      pageable:
        max-page-size: 50
  jpa:
    properties:
      hibernate:
        use_nationalized_character_data: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    open-in-view: false
  jackson:
    time-zone: UTC
  lifecycle:
    timeout-per-shutdown-phase: 20s

server:
  port: 8080
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: beans, health, info, metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: WARN
    io.github.balasis.taskmanager: INFO
    io.github.balasis.taskmanager.engine.monitoring: INFO
    org.springframework: WARN
    org.springframework.boot.web.embedded: INFO
    org.springframework.transaction.interceptor: WARN
    org.hibernate: WARN
    org.hibernate.SQL: WARN
    com.azure: WARN
    com.azure.monitor.opentelemetry: WARN
    com.zaxxer.hikari: WARN
    io.netty: WARN
    reactor: WARN
    org.flywaydb: WARN

app:
  jwt-secret-name: TASKMANAGER-JWT-SECRET
  download-threads: 15
  public-url: ${APP_PUBLIC_URL:http://localhost:5173}
